blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'blog.views.index', name='index'),
    #url(r'^blog/(?P<pk>\d+)/$', 'blog.views.index', name='post_list'),
    url(r'^blog/(?P<pk>\d+)/$', 'blog.views.post_detail', name='post_detail'),
    #url(r'^blog/(?P<pk>\d+)/edit$', 'blog.views.post_edit', name='post_edit'),
    url(r'^new/$', 'blog.views.post_new'),
]

lecture0525/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

# Create your models here.

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Postfields = '__all__'

blog/views.py
from django.http import HttpResponse
#from django.shortcuts import render
from django.shortcuts import redirect, render
from .models import Post
from .forms import PostForm

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', {'post_list':post_list})

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {'post':post})

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect('blog.views.index')
        else:
            form = PostForm()
        return render(request, 'blog/post_form.html'. {'form': form})
# Create your views here.

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Ask Django Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 60px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
</style>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Ask Django</a>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</div>

</body>
</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Ask Django</h1>
        <p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>
    </div>
</div>

<ul>
    {% for post in post_list %}
    <li>
        <a href="{% url "blog:post_detail" post.pk %}">
        {{post.title}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}

{{ post.title }}<hr/>

<img src="{{post.image.url}}"/><hr/>

{{post.content}} <hr/>

<a href="{% url "blog:index" %}"> 목록  </a>

{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>